name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Configuração do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Instalação de dependências
      - name: Install dependencies
        run: yarn install

      # Build do front-end
      - name: Build application
        run: yarn build

      # Validação do build
      - name: Validate build output
        run: test -d .next # Altere conforme o diretório gerado pelo build do seu projeto

      # Limpeza (opcional)
      - name: Clean up
        run: rm -rf node_modules
