name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # permite que o SonarCloud anote os PRs com os resultados da análise

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java (required for SonarScanner)
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Certifique-se de usar a versão suportada pelo SonarScanner
          distribution: 'temurin' # ou outra distribuição compatível, como zulu ou adopt

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=laraguilar_univet
            -Dsonar.organization=laraguilar
            -Dsonar.sources=src # Substitua pelo diretório de código-fonte do seu projeto
            # -Dsonar.tests=src   # Substitua pelo diretório de testes
            -Dsonar.language=ts
            -Dsonar.verbose=true
